export const REGISTER_USER_INIT = '@user/REGISTER_USER_INIT';
export const REGISTER_USER_SUCCESS = '@user/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = '@user/REGISTER_USER_FAILURE';


export const UPDATE_REGISTER_FORM = '@forms/UPDATE_REGISTER_FORM';
export const CLEAN_REGISTER_FORM = '@forms/CLEAN_REGISTER_FORM';


export const LOGIN_INIT = '@user/LOGIN_INIT';
export const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@user/LOGIN_FAILURE';


export const UPDATE_LOGIN_FORM = '@forms/UPDATE_LOGIN_FORM';
export const CLEAN_LOGIN_FORM = '@forms/CLEAN_LOGIN_FORM';


export const LOGOUT_INIT = '@user/LOGOUT_INIT';
export const LOGOUT_SUCCESS = '@user/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = '@user/LOGOUT_FAILURE';


export const FETCH_USER_DATA_INIT = '@user/FETCH_USER_DATA_INIT';
export const FETCH_USER_DATA_SUCCESS = '@user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = '@user/FETCH_USER_DATA_FAILURE';


export const DELETE_ACCOUNT_INIT = '@user/DELETE_ACCOUNT_INIT';
export const DELETE_ACCOUNT_SUCCESS = '@user/DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = '@user/DELETE_ACCOUNT_FAILURE';


export const UPDATE_DELETE_CONFIRMATION_FORM = '@forms/UPDATE_DELETE_CONFIRMATION_FORM';
export const CLEAN_DELETE_CONFIRMATION_FORM = '@forms/CLEAN_DELETE_CONFIRMATION_FORM';


export const UPDATE_USER_DATA_INIT = '@user/UPDATE_USER_DATA_INIT';
export const UPDATE_USER_DATA_SUCCESS = '@user/UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILURE = '@user/UPDATE_USER_DATA_FAILURE';

export const UPDATE_USER_DATA_FORM = '@forms/UPDATE_USER_DATA_FORM';
export const CLEAN_USER_DATA_FORM = '@forms/CLEAN_USER_DATA_FORM';


export const UPDATE_PASSWORD_INIT = '@user/UPDATE_PASSWORD_INIT';
export const UPDATE_PASSWORD_SUCCESS = '@user/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = '@user/UPDATE_PASSWORD_FAILURE';

export const UPDATE_PASSWORD_FORM = '@forms/UPDATE_PASSWORD_FORM';
export const CLEAN_PASSWORD_FORM = '@forms/CLEAN_PASSWORD_FORM';


export const FIND_PLAYERS_INIT = '@players/FIND_PLAYERS_INIT';
export const FIND_PLAYERS_SUCCESS = '@players/FIND_PLAYERS_SUCCESS';
export const FIND_PLAYERS_FAILURE = '@players/FIND_PLAYERS_INIT';
export const CLEAN_PLAYERS_LIST = '@players/CLEAN_PLAYERS_LIST';

export const UPDATE_FIND_PLAYERS_FORM = '@forms/UPDATE_FIND_PLAYERS_FORM';
export const CLEAN_FIND_PLAYERS_FORM = '@forms/CLEAN_FIND_PLAYERS_FORM';


export const GET_MESSAGES_INIT = '@messages/GET_MESSAGES_INIT';
export const GET_MESSAGES_SUCCESS = '@messages/GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = '@messages/GET_MESSAGES_FAILURE';


export const RECEIVE_MESSAGES_INIT = '@messages/RECEIVE_MESSAGES_INIT';
export const RECEIVE_MESSAGES_SUCCESS = '@messages/RECEIVE_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGES_FAILURE = '@messages/RECEIVE_MESSAGES_FAILURE';


export const SEND_MESSAGE_INIT = '@messages/SEND_MESSAGE_INIT';
export const SEND_MESSAGE_SUCCESS = '@messages/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = '@messages/SEND_MESSAGE_FAILURE';

export const UPDATE_SEND_MESSAGE_FORM = '@messages/UPDATE_SEND_MESSAGE_FORM';
export const CLEAN_SEND_MESSAGE_FORM = '@messages/CLEAN_SEND_MESSAGE_FORM';


export const GET_MATCHES_INIT = "@matches/GET_MATCHES_INIT";
export const GET_MATCHES_SUCCESS = "@matches/GET_MATCHES_SUCCESS";
export const GET_MATCHES_FAILURE = "@matches/GET_MATCHES_FAILURE";

export const UPDATE_CREATE_MATCH_FORM = "@forms/UPDATE_CREATE_MATCH_FORM";
export const CLEAN_CREATE_MATCH_FORM = "@forms/CLEAN_CREATE_MATCH_FORM";


export const CREATE_MATCH_INIT = "@matches/CREATE_MATCH_INIT";
export const CREATE_MATCH_SUCCESS = "@matches/CREATE_MATCH_SUCCESS";
export const CREATE_MATCH_FAILURE = "@matches/CREATE_MATCH_FAILURE";
export const CREATE_TOURNAMENT_MATCH_SUCCESS = "@tournaments/CREATE_TOURNAMENT_MATCH_SUCCESS";

export const UPDATE_UPDATE_MATCH_FORM = "@forms/UPDATE_UPDATE_MATCH_FORM";
export const CLEAN_UPDATE_MATCH_FORM = "@forms/CLEAN_UPDATE_MATCH_FORM";


export const UPDATE_MATCH_INIT = "@matches/UPDATE_MATCH_INIT";
export const UPDATE_MATCH_SUCCESS = "@matches/UPDATE_MATCH_SUCCESS";
export const UPDATE_MATCH_FAILURE = "@matches/UPDATE_MATCH_FAILURE";


export const FETCH_TOURNAMENTS_INIT = "@tournaments/FETCH_TOURNAMENTS_INIT";
export const FETCH_TOURNAMENTS_SUCCESS = "@tournaments/FETCH_TOURNAMENTS_SUCCESS";
export const FETCH_TOURNAMENTS_FAILURE = "@tournaments/FETCH_TOURNAMENTS_FAILURE";


export const FETCH_OWNED_TOURNAMENTS_INIT = "@tournaments/FETCH_OWNED_TOURNAMENTS_INIT";
export const FETCH_OWNED_TOURNAMENTS_SUCCESS = "@tournaments/FETCH_OWNED_TOURNAMENTS_SUCCESS";
export const FETCH_OWNED_TOURNAMENTS_FAILURE = "@tournaments/FETCH_OWNED_TOURNAMENTS_FAILURE";


export const UPDATE_ENTRY_INIT = "@tournaments/UPDATE_ENTRY_INIT";
export const UPDATE_ENTRY_SUCCESS = "@tournaments/UPDATE_ENTRY_SUCCESS";
export const UPDATE_ENTRY_FAILURE = "@tournaments/UPDATE_ENTRY_FAILURE";


export const DELETE_ENTRY_INIT = "@tournaments/DELETE_ENTRY_INIT";
export const DELETE_ENTRY_SUCCESS = "@tournaments/DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_FAILURE = "@tournaments/DELETE_ENTRY_FAILURE";


export const CREATE_ENTRY_INIT = "@tournaments/CREATE_ENTRY_INIT";
export const CREATE_ENTRY_SUCCESS = "@tournaments/CREATE_ENTRY_SUCCESS";
export const CREATE_ENTRY_FAILURE = "@tournaments/CREATE_ENTRY_FAILURE";


export const UPDATE_CREATE_TOURNAMENT_FORM = "@forms/UPDATE_CREATE_TOURNAMENT_FORM";
export const CLEAN_CREATE_TOURNAMENT_FORM = "@forms/CLEAN_CREATE_TOURNAMENT_FORM";


export const CREATE_TOURNAMENT_INIT = "@tournaments/CREATE_TOURNAMENT_INIT";
export const CREATE_TOURNAMENT_SUCCESS = "@tournaments/CREATE_TOURNAMENT_SUCCESS";
export const CREATE_TOURNAMENT_FAILURE = "@tournaments/CREATE_TOURNAMENT_FAILURE";


export const UPDATE_UPDATE_TOURNAMENT_FORM = "@forms/UPDATE_UPDATE_TOURNAMENT_FORM";
export const CLEAN_UPDATE_TOURNAMENT_FORM = "@forms/CLEAN_UPDATE_TOURNAMENT_FORM";


export const UPDATE_TOURNAMENT_INIT = "@tournaments/UPDATE_TOURNAMENT_INIT";
export const UPDATE_TOURNAMENT_SUCCESS = "@tournaments/UPDATE_TOURNAMENT_SUCCESS";
export const UPDATE_TOURNAMENT_FAILURE = "@tournaments/UPDATE_TOURNAMENT_FAILURE";


export const UPDATE_TOURNAMENT_MATCH_FORM = "@forms/UPDATE_TOURNAMENT_MATCH_FORM";
export const CLEAN_TOURNAMENT_MATCH_FORM = "@forms/CLEAN_TOURNAMENT_MATCH_FORM";
