export const REGISTER_USER_INIT = '@user/REGISTER_USER_INIT';
export const REGISTER_USER_SUCCESS = '@user/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = '@user/REGISTER_USER_FAILURE';


export const UPDATE_REGISTER_FORM = '@forms/UPDATE_REGISTER_FORM';
export const CLEAN_REGISTER_FORM = '@forms/CLEAN_REGISTER_FORM';


export const LOGIN_INIT = '@user/LOGIN_INIT';
export const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@user/LOGIN_FAILURE';


export const UPDATE_LOGIN_FORM = '@forms/UPDATE_LOGIN_FORM';
export const CLEAN_LOGIN_FORM = '@forms/CLEAN_LOGIN_FORM';


export const LOGOUT_INIT = '@user/LOGOUT_INIT';
export const LOGOUT_SUCCESS = '@user/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = '@user/LOGOUT_FAILURE';


export const FETCH_USER_DATA_INIT = '@user/FETCH_USER_DATA_INIT';
export const FETCH_USER_DATA_SUCCESS = '@user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = '@user/FETCH_USER_DATA_FAILURE';


export const DELETE_ACCOUNT_INIT = '@user/DELETE_ACCOUNT_INIT';
export const DELETE_ACCOUNT_SUCCESS = '@user/DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = '@user/DELETE_ACCOUNT_FAILURE';


export const UPDATE_DELETE_CONFIRMATION_FORM = '@forms/UPDATE_DELETE_CONFIRMATION_FORM';
export const CLEAN_DELETE_CONFIRMATION_FORM = '@forms/CLEAN_DELETE_CONFIRMATION_FORM';


export const UPDATE_USER_DATA_INIT = '@user/UPDATE_USER_DATA_INIT';
export const UPDATE_USER_DATA_SUCCESS = '@user/UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILURE = '@user/UPDATE_USER_DATA_FAILURE';

export const UPDATE_USER_DATA_FORM = '@forms/UPDATE_USER_DATA_FORM';
export const CLEAN_USER_DATA_FORM = '@forms/CLEAN_USER_DATA_FORM';


export const UPDATE_PASSWORD_INIT = '@user/UPDATE_PASSWORD_INIT';
export const UPDATE_PASSWORD_SUCCESS = '@user/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = '@user/UPDATE_PASSWORD_FAILURE';

export const UPDATE_PASSWORD_FORM = '@forms/UPDATE_PASSWORD_FORM';
export const CLEAN_PASSWORD_FORM = '@forms/CLEAN_PASSWORD_FORM';


export const GET_MESSAGES_INIT = '@messages/GET_MESSAGES_INIT';
export const GET_MESSAGES_SUCCESS = '@messages/GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = '@messages/GET_MESSAGES_FAILURE';


export const RECEIVE_MESSAGES_INIT = '@messages/RECEIVE_MESSAGES_INIT';
export const RECEIVE_MESSAGES_SUCCESS = '@messages/RECEIVE_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGES_FAILURE = '@messages/RECEIVE_MESSAGES_FAILURE';


export const SEND_MESSAGE_INIT = '@messages/SEND_MESSAGE_INIT';
export const SEND_MESSAGE_SUCCESS = '@messages/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = '@messages/SEND_MESSAGE_FAILURE';

export const UPDATE_SEND_MESSAGE_FORM = '@messages/UPDATE_SEND_MESSAGE_FORM';
export const CLEAN_SEND_MESSAGE_FORM = '@messages/CLEAN_SEND_MESSAGE_FORM';
